force-app/main/default/objects/Contact/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/SyncMessage__c.field-meta.xml
<CustomField>
    <fullName>SyncMessage__c</fullName>
    <label>Sync Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SyncWithOtherOrg.cls
public inherited sharing class SyncWithOtherOrg {
    
    private Set<Id> contactIds;


    // CONSTRUCTOR

    public SyncWithOtherOrg(List<Contact> contacts) {
        contactIds = new Map<Id, Contact>(contacts).keySet();
    }
    

    // PUBLIC

    public void execute() {
        if(!contactIds.isEmpty()) {
            sendToOtherOrg(contactIds);
        }
    }


    // PRIVATE
    
    @future(callout=true)
    private static void sendToOtherOrg(Set<Id> contactIds) {
        List<Contact> externalContacts = new List<Contact>();
        
        for(Contact contact : new ContactsSelector().byIds(contactIds)) {
            contact.ExternalId__c = contact.Id;
            contact.Id = null;
            externalContacts.add(contact);
        }
        
        try {
            List<SalesforceApi.Response> responses = new SalesforceApi().sendToOtherOrg(externalContacts); 
            persistSyncState(externalContacts, responses);           
        }
        catch(CalloutException ex) {
            persistSyncState(externalContacts, null);
        }
    }


    private static void persistSyncState(List<Contact> contacts, List<SalesforceApi.Response> responses) {

        for(Integer i = 0; i < contacts.size(); i++) {
            contacts[i].Id = contacts[i].ExternalId__c;
            contacts[i].SyncMessage__c = responses != null ? responses[i].message() : Label.CalloutError;
            contacts[i].ExternalId__c = responses != null ? responses[i].id : null;
        }
        
        // Note: Disable domain logic to avoid infinite loop
        fflib_SObjectDomain.getTriggerEvent(Contacts.class).disableAll();

        DMLManager.updateAsUser(contacts);
    }
}